midtermlascuna/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls'))

]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    #path('help/', views.help, name='help'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/update', views.update, name='update')
]

post/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    #question_text = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    #pub_date = models.DateTimeField('date_published')
    date_created = models.DateTimeField('date_created')
    date_updated = models.DateTimeField('date_updated')
    content = models.CharField(max_length=200)


    def __str__(self):
        #return 'Question:{}'.format(str(self.question_text))
        return 'Title:{}'.format(str(self.title))

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = 'comments')
    comment_text = models.CharField(max_length=200)

post/forms.py
from django.forms import ModelForm
from .models import Post

class PostModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from .forms import PostModelForm

# Create your views here.

def index(request):
    context = {}
    posts = Post.objects.all()
    context['posts'] = posts
    return render(request, 'index.html', context)

def detail(request, post_id):
    context={}
    context['post'] = Post.objects.get(id=post_id)
    return render(request, 'detail.html', context)

def update(request, post_id):
    context = {}
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponse('Post updated.')
        else:
            context['form'] = form
            render(request, 'update.html', context)
    else:
        context['form'] = PostModelForm(instance=post)
    return render(request, 'update.html', context)

post/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block head %}
        this is the title
      {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'post/materialize/css/materialize.min.css' %}">
    {% block styles %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
      123456
    {% endblock %}
    <script src="{% static 'post/materialize/js/materialize.min.js' %}">
    {% block scripts %}
    {% endblock %}
  </body>
</html>

post/templates/detail.html
{% extends 'base.html' %}

{% block head %}
this is the index page
{% endblock %}


{% block body %}
  <center>
  {{ post.title }} <br /><br />
  Date Created: {{ post.date_created }} <br />
  Date Updated: {{ post.date_updated }} <br /><br />
  {{ post.content }} <br /><br />

  Comments: <br />
    {% for comment in post.comments.all %}
      {{ comment.comment_text }} <br />
    {% endfor %}

  </center>
{% endblock %}

post/templates/index.html
{% extends 'base.html' %}
{% block head %}
this is the index page
{% endblock %}



{% block body %}
  <ol>
  {% for post in posts %}
  <li>
    <a href="{% url 'post:detail' post.id %}"> {{ post.title }} <br />
  </li>

  {% endfor %}
  </ol>
  <a class="btn btn-primary" href="http://127.0.0.1:8000/admin/post/post/add/">Create a new post</a>

{% endblock %}

post/templates/update.html
{% extends 'base.html' %}

{% block head %}
this is the index page
{% endblock %}

{% block body %}

<form action="{% url 'post:update' form.instance.id %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors}}
    {{ field.label }} {{ field }}
  {% endfor %}
  <input type="submit" value="Update">
</form>
{% endblock %}